ARG PHP_VERSION=8.4

FROM php:${PHP_VERSION}-cli-alpine

RUN apk add --no-cache \
        bash \
        git \
        icu-dev \
        linux-headers \
        oniguruma-dev \
        unzip \
        zip \
    && docker-php-ext-install \
        intl \
        mbstring \
        pcntl \
        pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY docker/php/serve-skeleton /usr/local/bin/serve-skeleton

WORKDIR /workspace
